parser: "@babel/eslint-parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - simple-import-sort
extends:
  - eslint:recommended
  - plugin:prettier/recommended
  - prettier
root: true
env:
  node: true
  jest: true
  browser: true
  es2021: true
rules:
  simple-import-sort/imports: "error"
  simple-import-sort/exports: "error"
