extends: existence
message: "Consider using `Business Unit(s)` or `Business Unit Group(s)` instead of `%s`."
link: "https://developers.google.com/style/inclusive-documentation"
ignorecase: true
level: error
tokens:
  - '(?:a|the)\s(?:store|shop|supermarket|chain)[s]?'
