extends: substitution
message: "Consider using '%s' instead of '%s'."
link: "https://developers.google.com/style/inclusive-documentation"
ignorecase: true
level: error
swap:
  '(?:store|shop|supermarket)s?': Business Unit(s) # Definition of business unit goes here
  '(?:store group|shop group|chain)s?': Business Unit Group(s)
  '(?:vendor|vendors)s?': Supplier(s)
  '(?:article)s?': Product(s)
